"""add is_active to assistants

Revision ID: 591f2c0ebd10
Revises: 3f9526359922
Create Date: 2026-01-15 15:13:57.203501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '591f2c0ebd10'
down_revision: Union[str, Sequence[str], None] = '3f9526359922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'is_active')
    # ### end Alembic commands ###
