"""add salebot_id

Revision ID: fb965ce070bc
Revises: 591f2c0ebd10
Create Date: 2026-01-16 12:33:11.641004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb965ce070bc'
down_revision: Union[str, Sequence[str], None] = '591f2c0ebd10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salebot_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salebot_id')
    # ### end Alembic commands ###
